### ISSUE TITLE
Differences btw GTK and QT keypress events

### ISSUE THREAD

**Issue by mhwombat** [mhwombat/textadept-hydra#7]
The problem is described in [https://github.com/orbitalquark/textadept/issues/301](https://github.com/orbitalquark/textadept/issues/301)

**Comment by mhwombat** [comment]
Pushed a fix to the repo.

@paaguti FYI

**Comment by rgieseke** [comment]
Thanks for fixing that!

**Comment by snoopy** [comment]
Currently <kbd>alt</kbd> seems to break hydra chains.

**Comment by mhwombat** [comment]
Mitchell's planning on a change where Textadept interprets keypresses so that plugins don't have to duplicate the logic. That should be available soon, so I will probably wait for that and see if the issue persists.

**Comment by mhwombat** [comment]
Mitchell made the change, so I've modified `textadept-hydra` accordingly and pushed the change.

If you get unexpected behaviour, you can temporarily uncomment the print statement in the `handle_key_seq` function in `init.lua` (at line 231 in this revision). That will show you the key sequence reported by Textadept.
